- adhocracy4/contrib/views.py
Permission view that does not redirect to login on authentication failure.
Needed, as the permissions for logged in users might be limited by the current phase. A redirect to login leads to redirect loop in such a case.
> add common permission view

- adhocracy4/contrib/apps.py
- adhocracy4/contrib/views.py
- tests/apps/questions/views.py
- tests/conftest.py
- tests/contrib/test_views.py
Extends the ordering functionality of the Django `generic.ListView`:
- Applies sort from the request parameter
- Adds supported orderings dict list
- Provides function get the ordering name
> add generic sort view

- adhocracy4/ratings/static/ratings/react_ratings.jsx
- hide icons for assistive technologies
- use simpler markup (before it used a lot of bootstrap helpers for a rather simple design)
- use the `disabled` property instead of the custom `is-read-only` class
Note that there are still some accessibility issues. The `isSelected` state and the overall semantics of the component are not yet properly exposed. We should definitely come back to that at some point.
I tested this with a4-meinberlin and it worked fine. (It needs CSS adjustments though)
> improve rating markup

- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments/static/comments/CommentReplyBar.jsx
While trying to style the a4 comments for meinberlin I found some issues with the markup:
- `<a href="#">` was used instead of `<button>`
- `class="icon fa-*"` was used instead of a `<i class="fa fa-*">` child (see [CSS in euth_wagtail](https://github.com/liqd/euth_wagtail/blob/40dd0be976073e92ca97a9041abcdc5c6a8c2350/euth_wagtail/assets/scss/components/_comments.scss#L73))
- `aria-hidden="true"` was used for essential elements
> comment markup improvements

- adhocracy4/emails/email.py
As I see it the behaviour of sending mails with multiple to entries is never wanted on a a platform. So I think we should change how sending email works.
> Send emails one by one to each receiver

- adhocracy4/contrib/views.py
- requirements/base.txt
Defines a view that integrates `django-filter`.
For an usage example see: https://github.com/liqd/a4-meinberlin/pull/86
> Filtered list view

- adhocracy4/images/widgets.py
As far as I understand the text input in the image yupload widget is only there for its visual appearance. It should therefore be excluded from the tab order.
> remove text input in image upload from tab order

- adhocracy4/projects/migrations/0005_auto_20170313_1407.py
Two 004 migrations were created in parallel. Recreating the ordering migration.
> resolve project migration conflict

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/templatetags/react_comments.py
- tests/comments/test_templatetags.py
The locale is a global setting and should not be set in a component.  Instead, we should call `moment.locale(django.languageCode)` in one central place (in the platform code).
The current version has the concrete issue that the locale is set to two different values: First to `django.languageCode` and then to `utils.translation.get_language()` on the first interaction.
> Do not set moment locale in comment code

- adhocracy4/modules/models.py
- adhocracy4/modules/templatetags/module_tags.py
- tests/modules/test_module_models.py
- tests/modules/test_module_templatetags.py
Add a helper function to check if any phase of a module provides a certain feature.
Add a templatetag to check if the module of an item has a feature in its phases. Using item instead of module here, as it directly provides the module and the item class.
> Module feature detection

- adhocracy4/api/mixins.py
- adhocracy4/api/routers.py
- adhocracy4/comments/api.py
- adhocracy4/comments/serializers.py
- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentList.jsx
- adhocracy4/ratings/api.py
- adhocracy4/ratings/serializers.py
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/static/api.js
- tests/comments/test_api.py
- tests/project/settings.py
- tests/project/urls.py
- tests/ratings/test_rating_api.py
This pull requests is the first of two trying to address #31. As mentioned in the ticket there are not enough informations in the comment API to implement proper rules for creation and listing of comment. The latter is currently solved by disabling listing in all relevant APIs (comment, reports, ratings).
In this pull-request the comment and rating api are prefixed with the content-type and object_pk of their subject.
`/comments/<pk>` ⇒ `/contenttypes/<content_type_pk>/objects/<object_pk>/comments/<pk>`
`/ratings/<pk>` ⇒ `/contenttypes/<content_type_pk>/objects/<object_pk>/ratings/<pk>`
Disadvantages:
- still not solved for reports (might not be required)
- for updating, deleting and detail view the context is not required (but still given)
- long urls
- custom router
There will be a …
> APIs for generic foreign keys

- adhocracy4/maps/static/a4maps/map_choose_polygon.js
The check that was done to do the `map.invalidateSize()` was too broad. When clicking 'result' first and then switching to the middle tab, the `mapVisible` was set already to true. Also: when resizing while not in that particular tab the bug would occur again as well. Now it's just on every click. We can observe if this will have any performance issues but I doubt it.
> fix bug with initially hidden map

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/reports/static/reports/ReportModal.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/reports/templatetags/react_reports.py
- tests/reports/test_report_templatetags.py
To make reporting available for arbitrary entries a new template tag
`react_reports` and an accompanying react function are introduced.
The template tag creates a link and the javascript to call the react
function to initialize the modal.
The modals is inserted as a new child of `body` to prevent problems when
the tag is used in f.ex. collapsible menus.
> Make reports available for arbitrary entries

- adhocracy4/projects/models.py
Do not feature archived projects anymore. This might become obsolet if we want to enable the user whether to filter or not.
> do not feature archived projects

- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/static/api.js
You'll need to update the call to documents endpoints. see: https://github.com/liqd/a4-meinberlin/pull/254/commits/04c6cc29d243c4a258034828305c4ec7718b9ab8 
Also adds a generic url replace logic.
Assuming you want to post to an endpoint's url `api/contenttypes/$contentTypeId/objects/$objectPk/comments/` you now make a call to `api.comments.change` with an object `urlReplaces` in data. JS will look for the keys `contentTypeId` and `objectPk` in that object and replace the placeholders in the url with the particular value in `urlReplaces`.
> refactor url replace logic and update documents api url

- adhocracy4/modules/predicates.py
- adhocracy4/phases/predicates.py
- adhocracy4/projects/rules.py
In https://github.com/liqd/adhocracy4/pull/60 we decided to use the permission terms view, add, change, delete.
Renaming the respective predicates for consistency.
> Consistent permission naming

- adhocracy4/static/api.js
The polls feature from meinberlin needs two JS api endpoints for managing poll options (/polls) and for voting on questions (/pollvotes).
> Add JS api for polls in meinberlin

- adhocracy4/api/mixins.py
- adhocracy4/follows/admin.py
- adhocracy4/follows/api.py
- adhocracy4/follows/apps.py
- adhocracy4/follows/migrations/0001_initial.py
- adhocracy4/follows/models.py
- adhocracy4/follows/serializers.py
- adhocracy4/follows/signals.py
- adhocracy4/follows/static/follows/FollowButton.jsx
- adhocracy4/follows/static/follows/react_follows.jsx
- adhocracy4/follows/templatetags/follow_tags.py
- adhocracy4/follows/templatetags/react_follows.py
- index.js
- tests/follows/conftest.py
- tests/follows/factories.py
- tests/follows/test_follow_api.py
- tests/follows/test_follow_signals.py
- tests/project/settings.py
- tests/project/urls.py
This ports the follows app from a4-opin to adhocracy4 core. There are some important things to note:
-   It is currently only possible to follow projects. In the future it might be a requirement to follow other things, e.g. items. It is not yet clear how this will work exactly. It will probably be implemented as a separate (but related) feature. We think that using generic foreign keys is overkill here.
-   The react component does not currently support the case where the user is not logged in. For now, the recommended bahvior in this case is not to show the component. See https://github.com/liqd/a4-opin/issues/629 and https://github.com/liqd/a4-opin/issues/627 for related issues in a4-opin.
-   There is some discussion as to whether the API of this feature should be changed. This pull …
> add project follows

- adhocracy4/categories/models.py
- tests/apps/questions/migrations/0003_remove_related_set.py
If concrete categorizable Items in different apps have the same Modelname, the related field reference on the category clashes. (For example `budgeting.models.Proposal` and `kiezkasse.models.Proposal` would bost result in the same `Category.proposal_set`)
As there is no real usecase to get the related items of a specific type from a Category object i propose to remove the backwards field reference
> Remove the category related field name.

- adhocracy4/actions/migrations/0001_initial.py
- adhocracy4/categories/migrations/0001_initial.py
A4 migrations fail with an empty postgres database because of these missing initial migrations.
Breaking, as these migrations will fail if the tables already exist.
Suggested solution, manually fixing by:
`./manage.py migrate --fake a4actions 0001_initial`
`./manage.py migrate --fake a4categories 0001_initial`
> Add missing initial migrations

- adhocracy4/filters/filters.py
- tests/filter/test_paged_filterset.py
By default FilterSets from django_filter are keeping every non filter
argument in the query string. This results a problem when paging is used
in addition to filters (see liqd/a4-meinberlin#403)
It is desired to reset the page to zero when applying a filter. This PR
introduces a PagedFilterSet which removes the page argument from the
query string.
> Add a paging aware filterset.

- adhocracy4/filters/filters.py
QueryDicts are inheriting from MultiValueDicts which act different then dicts
on updates, as:
"update() extends rather than replaces existing key lists."
This commit will set the default filter value only if it has not been manually
set yet.
Fixes liqd/a4-meinberlin#490
> Fix DefaultsFilterSet

- adhocracy4/projects/signals.py
Currently the signals are registered explicitely for the Project base model. In
meinBerlin we inherit from the base model to enable external projects and
bplans. As Django signals do not take inheritance into account when handling
signals, it is required to register signals without binding to a sender and
check if the senders type is a subclass of Project manually.
If, for example for performance reasons, a general signal receiver is not wanted in the core, we could add explicit signal handlers for two inherited project types we had to implement.
> Enable signals for inheriting projects.

- adhocracy4/actions/management/commands/create_system_actions.py
- adhocracy4/actions/migrations/0002_add_START_verb.py
- adhocracy4/actions/signals.py
- adhocracy4/actions/verbs.py
- adhocracy4/phases/models.py
- tests/actions/test_commands.py
The start of a project ist defined with an Action with the verb START
and the project as the object.
A START action will be created if a project first phase starts within
the next hour.
> Add START verb and signal start of projects

- adhocracy4/emails/__init__.py
To allow for translated emails the overwriteable `get_languages` method
is introduced. It gets the receiver as an attribute an may be
overwritten to send Emails according to (not yet available) user
settings.
Currently the currently set language is used, which is set from the
browsers language settings if the call results from a user request or
from `settings.LANGUAGE_CODE`.
> Add overwriteable get_languages method to emails

- adhocracy4/modules/predicates.py
Before the module predicates did allow to change, rate, et al. items  of unpublished projects if the phase did allow it.
> Check if project is live in module predicates

- adhocracy4/actions/signals.py
- tests/actions/test_signals.py
As we are loosing all the information when the object of an action is
deleted, the action itself may be deleted, too.
> Delete Actions if the related object is deleted

- package.json
Before a warning was emitted on `node install`:
```
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-import@>=2.2.0 but none was installed.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-node@>=4.2.2 but none was installed.
```
and linting failed with:
```
⌂ ~/g/adhocracy4 » make lint                                                                                                                                                             2017-06-as-async-emails ✗
. ./bin/activate && node_modules/.bin/polylint
node_modules/.bin/polylint: 1: eval: flake8: not found
Oops! Something went wrong! :(
ESLint couldn't find the plugin "eslint-plugin-import". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make …
```
> Add eslint plugin dependencies

- adhocracy4/actions/management/commands/create_system_actions.py
- tests/actions/test_commands.py
The START action should include the actual objects start timestamp. If a project start is rescheduled the original START action has to be adapted.
This is different from the SCHEDULE action, where the timestamp is in relation to the action itself.
In opin the SCHEDULE action is not used to send the "ends in 24 hours/soon" email, but a COMPLETE action which is not in a4 core yet.
While i agree to use  the phase.end_date as the timestamp for the COMPLETE action, i'd argue to keep the time when the action was created as the timestamp for the SCHEDULE action.
@xi @slomo  what is your opinion on
The START action and the modifications to SCHEDULE were initially introduces in #108
> Set the START project actions timestamp to the actual phases start_date

- adhocracy4/maps/static/a4maps/map_choose_point.js
- adhocracy4/maps/static/a4maps/map_choose_polygon.js
- adhocracy4/maps/static/a4maps/map_display_point.js
- adhocracy4/maps/static/a4maps/map_display_points.js
- package.json
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md
This updates leaflet to 1.0.3. All changes I made should be backwards compatible.
I testes all four map types and found no further issues. leaflet.draw also seemed to work fine with the new version.
I encountered on strange issue: Yesterday, when ever I was on a page that had leaflet loaded, I was unable to scroll the page. However, today I could not reprodce the issue anymore.
See also https://github.com/liqd/a4-meinberlin/pull/544 for further changes that might be required for individual platforms.
> update leaflet to 1.0.x

- adhocracy4/maps/migrations/0002_change_help_text.py
- adhocracy4/maps/models.py
the default help text is "enter valid JSON". It can not be blank (see https://github.com/dmkoch/django-jsonfield/issues/95)
see also https://github.com/liqd/a4-meinberlin/issues/503
> overwrite polygon default help text

- adhocracy4/filters/filters.py
- adhocracy4/filters/views.py
- passes the queryset from the list view to the filter instead of the filter using `$model.objects.all()`
- allows to prefilter the queryset with the `queryset` option of the view.
- allows to pass additional arguments to the FilterSet initializer from views extending the FilteredListViews
- use case was to filter ideas on a profile based on which users profile I am currently viewing
I am pretty confident that the first feature should not make any issues, but still marking this breaking.
> Allow to override kwargs in FilteredListViews

- adhocracy4/maps/static/a4maps/map_choose_polygon.js
fixup to #107
If polygon was undefined (e.g. when creating a new project) bbox was used. bbox is not a polygon.
The issue is fixed by returning bounds directly.
See also https://github.com/liqd/a4-meinberlin/pull/544/commits/895ab6aa55fb33192d729f8be7aeeaaae9af007c
> fix getBasePolygon

- adhocracy4/actions/migrations/0003_set_default_ordering_to_timestamp.py
- adhocracy4/actions/models.py
- tests/actions/conftest.py
- tests/actions/factories.py
- tests/actions/test_models.py
-  extend queryset with `exlude_update` and `filter_public` (used in mB and AE)
- make type and icon properties of Action (removes need for Proxy model)
-  allow each project to configure its icons and types
- change default ordering to descending by creation time
Example usage: https://github.com/liqd/a4-advocate-europe/pull/187
> Extend actions properties and queryset

- adhocracy4/images/validators.py
Fixes https://github.com/liqd/a4-meinberlin/issues/616
Validation of SVG images failes on `image.width`, as it does not have a width.
Raising directly, if the image format is not supported.
> Fix image validation

- adhocracy4/comments/static/comments/CommentBox.jsx
- package.json
The react version (or rather react-addons-update) we are currently using relies on `Object.assign` to be native. IE11 obviously has that not implemented and breaks. 
This PR updates react (https://github.com/facebook/react/pull/9932) and introduces a dependency called ['immutability-helper'](https://github.com/kolodny/immutability-helper) which replaces the deprecated 'react-addons-update. 
Wherever you use that dependency you simply have to replace it:
```js
// var update = require('react-addons-update')
var update = require('immutability-helper')
```
E.g. here: https://github.com/liqd/a4-opin/blob/06bb71e02caf83f2f7057a4cc7e51c35ec18bee1/euth/documents/static/documents/ParagraphBox.jsx#L5
Advocate Europe does not seem to use that one (yet).
> update react: fix IE11 incompatibility

- adhocracy4/test/helpers.py
- tests/conftest.py
Since models.py and signals (from app.ready()) are loaded before the
conftest.py is evaluated it is required to reload the module from which
the patch decorator is used.
This PR extends the patch_background_task_decorator to allow for a list
of module names where the task decorator is used and which have to be
reloaded to apply the patch.
P.S. Until now the patching did work because core emails are only loaded
from the DRF api.py which is loaded after the conftest.py is evaluated.
But in meinBerlin we realised that the emails send from models/signals
were still handled by background_task
> Fix background task decorator patching

- adhocracy4/comments/static/comments/Comment.jsx
- package.json
This allows us to dump moment.js. 
This is not breaking, but I still suggest to remove lines located in webpack.config (e.g. https://github.com/liqd/a4-opin/blob/ae114fc8c5bd010dec9b0736f5dd316cd5932bb7/webpack.config.js#L37) or package.json.
> remove moment

- MANIFEST.in
Adding `static` and `templates` of all apps to the package, to avoid forgetting to add templates of new apps.
@slomo: Or was there a good reason to add them manually?
> Add all static and template folders recursively to package

- adhocracy4/images/static/a4images/imageUploader.js
- adhocracy4/images/templates/a4images/image_upload_widget.html
- adhocracy4/images/widgets.py
this improves accessibility for the image upload as well as immediately updates the file name when changing/uploading the image. 
Checking opin and AE, I haven't found an html override of `image_upload_widget.html` so this should not be breaking.
fixes #105
> improve image upload

- adhocracy4/follows/static/follows/FollowButton.jsx
Clicking the button now opens a dropdown where the specific action is explained.
This is breaking because it requires additional styling. See https://github.com/liqd/a4-meinberlin/pull/728. At least setting
```css
.select-item-desc {
display: block;
}
```
is recommended, since I couldn't use any block elements due to then invalid html.
> ui to explain follow

- adhocracy4/comments/rules.py
- adhocracy4/ratings/rules.py
The predicate, which is tested to decide if comments can be rated, commented, changed, or deleted checked if the phase allowed commenting. Instead it should check and does check now if commenting is allowed for that content_type, like in the comment create rule.
From now on, you'll have to make sure, that you test for the phase in the rule in your project. But you will test it there anyway, otherwise commenting would be allowed, even if the phase doesn't.
> check if commenting is allowed for check if comments can be rated, commented, changed, or deleted

- adhocracy4/filters/templates/a4filters/widgets/free_text_filter.html
Having the action attribute empty is invalid HTML, omitting it will send the data to the current page.
> remove empty action attribute

- adhocracy4/comments/rules.py
- adhocracy4/modules/predicates.py
- adhocracy4/organisations/predicates.py
- adhocracy4/phases/predicates.py
- adhocracy4/projects/predicates.py
- adhocracy4/ratings/rules.py
This PR enables django permissions work together with our rules system. Without these changes it is not possible to create a group with certain table-based permissions within the django admin, because the names of our rules have the same name pattern as djangos permissions. 
When the django admin is created django checks all permissions available if one of them returns true, but runs in an error when trying to call a predicate in one of our customs rules, as no project or item (whatever the permission_object is) is set. 
Another solution to fix this, would have been to change the name pattern of our rules, but we preferred this solution, as no more adaptions should be necessary now.
> fix predicates to return False if argument is None

- adhocracy4/follows/static/follows/FollowButton.jsx
see also https://github.com/liqd/a4-meinberlin/pull/787
we got the feedback that the connection between "email", "notification", and
"follow" is not completely clear.
@janaba what do you think of this change?
> clearify connection between "follow" and "email"

- adhocracy4/images/templates/a4images/image_upload_widget.html
HTML was invalid before. It's easier than  removing the img tag and dynamically inserting one via JS because that would require a bigger rewrite of the js upload code.
The picture is invisible, it's a transparent gif.
> fallback tiny image for image upload without picture

- adhocracy4/maps/static/a4maps/map_choose_point.js
This allows to add alternative input methods, e.g. search by address.
Note that you have to trigger the change event manually, e.g.:
$('id_' + name)
.val('{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[13,52]}}')
.trigger('change')
> update marker when input changes

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments/static/comments/CommentReplyBar.jsx
- adhocracy4/static/Modal.jsx
- package.json
React emitted the appended warning that using `React.PropTypes` is
depreacted in favor of the separate package 'prop-types'. This PR adapts
to these changes.
> Accessing PropTypes via the main React package is deprecated, and will
> be removed in  React v16.0. Use the latest available v15.* prop-types
> package from npm instead. For info on usage, compatibility, migration
> and more, see https://fb.me/prop-types-docs
> Use prop-types package (fixes react deprecation warnings)

- adhocracy4/follows/static/follows/FollowButton.jsx
fixes https://github.com/liqd/a4-meinberlin/issues/832
I am not really sure why string extraction doesn't work here. I guess that django is confused about some JSX.
> workaround string extraction bug in followButton

- package.json
With python, we do not pin dependency versions in this repo, but on the concrete projects (meinberlin, opin, …). I propose to do the same with npm.  This prevent version conflicts and installing two versions of the same library.
> use caret version range for npm dependencies

- adhocracy4/test/factories/__init__.py
Replace the "text" faker with the "sentence" faker in places where a name/title is expected. 
Using "text" may result in newlines which does not work with email subjects.
This kind of fixes #200 although it might be possible that the database length validation may be violated.
> Fix fakers for project names (titles)

- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/templatetags/react_comments.py
- adhocracy4/ratings/templatetags/react_ratings.py
- adhocracy4/rules/apps.py
- adhocracy4/rules/discovery.py
- adhocracy4/rules/templatetags/discovery_tags.py
- tests/apps/questions/rules.py
- tests/comments/test_templatetags.py
- tests/project/settings.py
- tests/ratings/test_rating_templatetags.py
- tests/rules/test_rule_templatetags.py
Adds a "normal user", who has no special permissions, but checks if a logged-in user would be allowed to do whatever the button promises.
The template tag can be used analogous to has_perm from the rules tags. Like here: https://github.com/liqd/a4-opin/pull/962/files
For the comments, the link "Please login to comments" is only displayed, when commenting is possible.
> add normal user and template tag to discover cta-buttons

- adhocracy4/categories/fields.py
- adhocracy4/categories/forms.py
The category fields had not been translated as the field had been
reinitialized instead of modified. With this PR the auto generated field
(with its localized verbose_name) will be kept and adapted to the
filtered queryset.
Furthermore the required parameter is set to true if there are any
categories for the module.
> Make category field translateable

- adhocracy4/maps/static/a4maps/map_choose_point.js
- adhocracy4/maps/static/a4maps/map_choose_polygon.js
In meinberlin we have a script that warns users before leaving a changed form. This fixes that script for maps.
> trigger change events on maps

- adhocracy4/static/api.js
As we have to enable Multiple Choices for the meinBerlin poll feature we decided to rewrite the voting api by introducing a proper QuestionRouter. 
This PR adapts the core api.js to the new meinBerlin API Interface
Before a weird hacky solution was used, where a put was sent, that contained the Question id as `pk` kwarg, altough in the end a Vote object was either updated or created.
Note: this PR is breaking for meinBerlin until we merge the accompanying PR
> Adapt meinBerlin poll/vote api.js to QuestionRouter

- adhocracy4/images/signals.py
With multi table inheritance the image fields from the parent models
have been added multiple times to the image_fields list.
This limits the fields that may be added to the models concrete fields
and additionally ensures overwritten fields may not be added twice.
> Prevent image fields from being multiple registered in case of multi table inheritance

- adhocracy4/forms/widgets.py
As the DateTime Field declares the time part as optional with a fallback
to a default value, the associated input element as declared by the
widget may never be declared as required.
Fixes #187
> Ensure time input field of DateTime is always optional.

- adhocracy4/modules/models.py
- adhocracy4/projects/models.py
In a4-product we patch reverse to have support for the partner middleware.  However it works only with kwargs.
Fixed the reverse usage here, to be able to use get_absolute_url of project and module in a4-product.
> Use kwargs with reverse

- adhocracy4/projects/mixins.py
- adhocracy4/projects/views.py
- adhocracy4/test/helpers.py
- tests/projects/test_mixins.py
Implements the project/module view helper suggested in #134
Replaces  #185 and #115
It sets two properties `project` and `module` on each inheriting view. 
The properties may be derived
1. directly from a `project` or `module` kwarg as set by the Phase- and ModuleDispatcherMixin
2. from a configurable url parameter which defaults to `project_slug` and `module_slug`
3. from the object returned by `get_object` if the view property `get_context_from_object = True`
This PR is currently breaking due to commit 286d7bc4316a5613c9580 which removed the `phase` property from the mixin. It is not clear if the `phase` property is required by opin or if it is replaced by the `ProjectPhaseMixin`.
This is a copy of the working solution from a4-meinberlin and could be used in the core dashboard as well.
> Project Mixin extension

- adhocracy4/emails/base.py
- adhocracy4/emails/mixins.py
This fixes #174 by replacing newlines from the subject.
Furthermore it makes the SyncEmailMixin a real Mixin again by removing it's inheritance from EmailBase. This may be breaking if
* SyncEmailMixin was used as the sole dependency of a concrete Email implementation
* SyncEmailMixin was defined after the Email or EmailBase dependency
In those cases the application code has to be adapted and the SyncEmailMixin used like:
```
from adhocracy4.emails import Email
from adhocracy4.emails.base import EmailBase
from adhocracy4.emails.mixins import SyncEmailMixin
class SomeEmail(SyncEmailMixin, EmailBase):
pass
class SomePlatformMixinEmail(SyncEmailMixin, Email):
pass
```
> Strip newlines from email subjects and make SyncEmail a Mixin again

- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/static/config.js
fixes #32
Note that `window.adhocracy4.getCurrentPath()` is used. In the default case, this just returns `window.location.path`. We need to be able to overwrite this for embedding in meinberlin.
This is breaking because `config.loginUrl` is removed.
> set next parameter when redirecting to login from js

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/static/comments/CommentList.jsx
- adhocracy4/static/Alert.jsx
This adds error messages when creating or editing comments fails. I tested it by stopping the server after I had loaded the page.
I am not all too happy with this PR. It does what it is supposed to be, but I found it hard to find my way around the comment code, simply because it is complex already. I hope I was able to refactor my additions to a point where review is possible.
Fixes #95
> Add error handling for comments

- adhocracy4/comments/static/comments/Comment.jsx
due to an error with gettext it is not possible to use ngettext if the %s placeholder occurs only in the plural form.
> Workaround gettext error for plural forms

- adhocracy4/maps/static/a4maps/map_display_points.js
- adhocracy4/maps/templatetags/maps_tags.py
An alternative would be to use something like:
```
function escapeHtml(unsafe) {
return unsafe
.replace(/&/g, "&amp;")
.replace(/</g, "&lt;")
.replace(/>/g, "&gt;")
.replace(/"/g, "&quot;")
.replace(/'/g, "&#039;");
}
```
a similiar solution is [used in underscore.js](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1462)
i did not create the function as a contrib helper function, as the map_display_points.js is currently not handled by babel. if we need it somewhere else, we should move it to `adhocracy/static` and import it with babel. this would require to adapt our webpack scripts.
@fuzzylogic2000  @MagdaN @mkind 
are you okay with this fix? in addition i would like to merge the CSP PRs. and we can still think about sanitizing every user entered text field
> Escape html in feature name used for map popups

- adhocracy4/modules/models.py
- adhocracy4/projects/models.py
- tests/modules/test_module_models.py
Ha! It does make a difference:
When viewing 4 projects in meinberlin there are 39 queries without this, with this changes it's "only" 30 queries.
As you can see in the changes for the test there is a slight change in behavior, that is that the value of a property may not change anymore when called multiple times, but I don't think we rely on that in the code.
> cached properties

- .gitignore
- adhocracy4/ratings/api.py
- adhocracy4/ratings/static/ratings/react_ratings.jsx
When a user has two tabs with the same page open and rates an item
in both of them, this will crash in the second tab if the user
has not previously rated the item before page load.
The reason is that we decide based on information from page load
whether we call 'create' or 'update' of the rating. If we call
'create' twice, it crashes.
This patch fixes the issue by making the API check whether a
rating exists already and returning the corresponding ID if
it is the case. The frontend again uses the ID to issue
an 'update' request.
This requires an additional roundtrip to the user, but keeps
the internal logic as simple as possible.
Fixes #293
> ratings: fix crash on double creation

- tests/helpers.py
This fixes all but one warning concerning naive datetime
> tests: make helpers.py use timezone.now

- adhocracy4/projects/models.py
As the days left are also a property and we might need the percentage elsewhere, it made sense (to me) to add it here.
But we also need something like https://github.com/liqd/a4-opin/blob/master/euth/projects/templatetags/time_delta_tags.py in meinBerlin. I am unsure where or how to add that, though. we have the days_left in the properties, but these are very coarse (because hours, minutes and seconds of timezone.now are set to zero). In meinBerlin we want days, hours and minutes and need that in the storefront and the participation overview. I don't know how to add the whole thing into the properties, because we might need to do translations with sentences. We could only add seconds_left and add the other stuff in the respective project, but that also doesn't seem too sensible. ???!!
> add progress of active phase as property to project

- adhocracy4/polls/views.py
In the `get` method, the 404 exeption handler first sets `self.object = None`
and then calls `self.get_context_data`, which doesn't expect `self.object`
to be None. Add a check for that case.
Fixes https://sentry.liqd.net/sentry/opin-prod/issues/182/
> polls: fix crash if poll wasn't found

- adhocracy4/projects/admin.py
The topics field was breaking the projects without topics. As the only place (mB) where topic and location are actually used overwrites the project-admin anyway, we removed it here.
> remove the topics and location from the projects django admin

- adhocracy4/comments/signals.py
With the field modified not being modified anymore, when a comment or idea is saved in this signal, this didn't work anymore for ideas, where the last discussion was an added child-comment.
> fill last discussed with newer of last discussed and created

- adhocracy4/modules/models.py
I think we have to use participation_dates as their might be events, right?
> modules: Fix get_timeline_index function

- Makefile
- adhocracy4/actions/management/commands/create_system_actions.py
- tests/actions/test_commands.py
* rename _phase_end_tomorrow -> _phase_ends
* rename _project_start_last_hour -> _project_started
* read number of hours from config if available
* add '_phase_started' - like _project_started, for multimodules
and some more, see commits
> actions: Refine system actions

- tests/polls/test_models.py
This was previously not detected as we run our tests on travis without
`--reuse-db`. With a fresh database, this test would coincidentally
compare two ids with the value `1`, but from different tables.
Propperly compare choice to choice instead.
> tests/polls: Compare user_choices_list to a choice, not a vote

- adhocracy4/projects/models.py
will fix https://github.com/liqd/a4-meinberlin/issues/2658
and adds a property for unpublished modules
> apps/projects: add property for unpublished modules

- adhocracy4/comments/models.py
- adhocracy4/comments_async/static/comments_with_categories/comment.jsx
This will solve (the a4-part) of https://github.com/liqd/adhocracy-plus/issues/285
But it will break some translations for the other projects when updating, so we need to redo them then.
> translations: mark context of word comment

- adhocracy4/exports/mixins.py
Instead of throwing a 500 error, just return an empty result. Fixes https://sentry.liqd.net/sentry/meinberlin-prod/issues/962/
> exports/mixin: Fail softly if geometry is not set

- adhocracy4/modules/models.py
- adhocracy4/phases/models.py
- adhocracy4/projects/models.py
- docs/phases_and_modules.md
This does not change any properties only reordered them. Oh, and deprecates is_first_phase (a function in the phase model, which seems to be used for the actions).
> Ka 2020 02 project properties

- adhocracy4/categories/assets/category_formset.js
- adhocracy4/categories/assets/select_dropdown_init.js
- adhocracy4/images/assets/image_uploader.js
- adhocracy4/maps/static/a4maps/a4maps_choose_point.js
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/maps/static/a4maps/a4maps_display_point.js
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
- adhocracy4/static/api.js
When using multple webpack endpoints we do not get a global jQuery
object but instead one for each endpoint. These do not see each others
signals, thus do not fire.
Use standard js events instead - they don't suffer from that problem and
we should get rid of jQuery anyway over time.
Also use the chance to clean up the init syntax.
> assets: Replace jQuery 'a4.embed.ready' listeners with vanilla js

- adhocracy4/maps/static/a4maps/a4maps_display_points.js
This was actually already working! This is a small change and then it will fix https://github.com/liqd/a4-meinberlin/issues/1932 to everyones happiness!
> apps/maps: show no of comments even when no rating is shown

- renovate.json
Most importantly automerge patch updates, i.e. 1.0.x for "runtime" dependencies (it's
actually only used during build) and also minor updates, i.e. 1.x.x for
dev dependencies.
> renovate: Use the same settings as other projects

- adhocracy4/categories/assets/category_formset.js
- adhocracy4/categories/assets/select_dropdown_init.js
- adhocracy4/static/select_dropdown.js
The global $ is now usually provided by Webpack - unfortunately that
does not play well with registering jQuery plugins, as the global
jQuery object is not shared between endpoints (or read-only?).
Closes https://github.com/liqd/a4-meinberlin/issues/2935
> assets: Register jQuery plugins to window.jQuery

- adhocracy4/comments_async/static/comments_async/comment_form.jsx
This will fix https://github.com/liqd/adhocracy-plus/issues/730
> comments_async/comment_form: only apply autofocus for debate module

- docs/roles_and_permissions.md
`./` Already refers to the current folder.
> docs: Fix a link

- adhocracy4/comments_async/static/comments_async/comment.jsx
Like we do for the old comments.
Closes #625
> comments_async: Hide report button for non-authenticated users

- adhocracy4/exports/views.py
fixes that none values are exported as string "None" like on https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/plans/
> apps/export: export empty string if value is none

- .eslintrc
- adhocracy4/maps/static/a4maps/a4maps_choose_point.js
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/maps/static/a4maps/a4maps_display_point.js
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
- adhocracy4/static/global_jquery.jsx
- adhocracy4/static/widget.js
- index.js
This way we can finally remove the alias magic in webpack from
our frontends.
Also some more cleanups and ES6 ports.
> index: Add common map functions to exports

- adhocracy4/maps/static/a4maps/a4maps_common.js
Properly include the passed in attribution - this was overlooked
during the initial implementation.
> maps/assets: Add leaflet attribution layer to vector maps

- adhocracy4/static/global_jquery.jsx
This code runs unconditionally when importing anything from adhocracy4
via node/ES5 `require`. Depending on order, this would make us
overwrite an existing `window.jQuery` instance - which may have been
extented by e.g. `select2`, which then broke.
> static: Avoid reinitializing window.jQuery

- adhocracy4/modules/models.py
- adhocracy4/projects/models.py
- tests/modules/test_module_models.py
- tests/projects/test_project_model_module_properties.py
- tests/projects/test_project_model_phase_properties.py
fixes https://sentry.liqd.net/organizations/sentry/issues/1293
I didn't know how to get that error manually, so added the tests to do that.
> apps/projects and modules: add time_left property for < 1 second

- .editorconfig
- Makefile
With this, isort doesn't check the migrations, but flake8 still does, I couldn't fix that. :(
> settings: make isort not check migrations even when passed as argument

- adhocracy4/polls/static/polls/Question.jsx
In Question.jsx a bug around 'showing preliminary results' button is fixed
Additionally following bugs to go back 'to poll' and 'change vote' buttons
are also fixed.
Fixes #2106 (a4-opin repo though)
> apps/questions: fixing poll buttons

- adhocracy4/dashboard/mixins.py
- tests/dashboard/test_views.py
This avoids having no moderators in a project.
Fixes https://github.com/liqd/adhocracy-plus/issues/1063
> apps/dashboard: copy moderators over on project duplicate

- adhocracy4/polls/rules.py
to make it behave like other modules, we show the content of the poll also prior to project start.
Does not affect opin, because the content of the participation is always only shown after project start, no matter what the rule is. For other projects it does not make sense to show a 403 because the project hasn't started yet, even though it's already published.
> apps/polls: also show poll before project start

- adhocracy4/polls/api.py
- adhocracy4/polls/models.py
- adhocracy4/polls/serializers.py
- adhocracy4/polls/static/polls/PollManagement.jsx
- tests/polls/conftest.py
- tests/polls/factories.py
- tests/polls/test_models.py
- tests/polls/test_question_api.py
- tests/polls/test_validators.py
- tests/polls/test_vote_api.py
Tests for new serializers are still missing, but there is a task in taiga and I wanted to wait until we are sure that this is the way to do it.. 
The serialized data can be seen by adding mixinx.RetrieveModelMixin to PollViewSet in polls/api.py . Then /api/polls/pollId shows all questions of the poll (although the vote annotations arent there, as the questions are only annotated in the VoteViewSet and not in the PollViewSet). I tested with Opin, hope it also works in mB :nerd_face:
> polls/models: add validation before save

- requirements/base.txt
psycopg 2.9.x is incompatible with django 2.2.x so pin to the latest release and make pyup ignore it.
> requirements/base: psycopg2 >= 2.9 is incompatible with django 2.2.x

- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/maps/static/a4maps/a4maps_common.js
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
Described in project mB (link to issue):
https://github.com/liqd/a4-meinberlin/issues/3633
A bug in leaflet, which leads to that issue in Safari (and Firefox).
https://github.com/Leaflet/Leaflet/issues/7266
> apps/budgetingmap/maps: fixing inactive pins (safari & FF)

- adhocracy4/polls/assets/PollQuestions.jsx
This will fix https://github.com/liqd/a4-meinberlin/issues/3736 and https://github.com/liqd/a4-meinberlin/issues/3735 once updated.
> apps/polls: only show poll initially when phase active

- adhocracy4/projects/models.py
We need this to make the poll detail view work with plattforms with and without timeline.
Once updated will fix https://github.com/liqd/a4-opin/issues/2282
> apps/projects: test if field event_type exists in offile event

- adhocracy4/exports/mixins/comments.py
- adhocracy4/exports/mixins/general.py
- tests/exports/mixins/test_general_mixins.py
Closes part of #3793, the other one was fixed in a4-meinberlin.
> exports/mixins: fixed export time difference and test

- adhocracy4/polls/assets/PollQuestions.jsx
This fixes the problem with the showing the result not working at all. 
It was introduced with https://github.com/liqd/adhocracy4/pull/822
But I don't think this works as intended (and before also didn't). But I would like to merge, update and then ask @mcastro-lqd and @CarolingerSeilchenspringer how it should behave. There is also the other slightly weird thing where you can click "view result", even if you changed your vote and then the result is shown, but with the uservote checkmark at the wrong option.
> apps/polls: use new state to determine which poll link to show

- package.json
add to other apps on update:
`   fallback: {
path: require.resolve('path-browserify'),
assert: require.resolve('assert/')
},`
> fix(deps): update dependency remark-gfm to v2

- adhocracy4/comments_async/serializers.py
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_list.jsx
In the 3rd commit:
Changed the mechanism defined in the serializer to block comments from showing in conversation that have been set blocked by moderation. This time it should work correctly.
As of 2nd commit:
Texts of blocked comments are not shown, but marked as blocked instead. Child comments of blocked comments are still displayed:
As discussed, this is only implemented for async comments.
> Sm 2021 11 blocked comments not shown in discussion

- tests/comments/test_async_serializer.py
This test is written based on https://github.com/liqd/a4-meinberlin/blob/main/tests/plans/test_serializer.py
@fuzzylogic2000 it produces the following error message:
E               TypeError: Comment() got an unexpected keyword argument 'comments'
I presume I'm not understanding how to translate the example to the comment, comment list and serializer.
> tests/comments: test async comment serializer

- adhocracy4/comments/rules.py
- adhocracy4/modules/predicates.py
- adhocracy4/polls/rules.py
- adhocracy4/projects/predicates.py
- adhocracy4/ratings/rules.py
- tests/modules/test_module_predicates.py
- improves naming of one predicate
- fixes #927
- adds project group members to the tests
There is more to do, but this is a start. :) And with that, we can also work on the rules in mB and make all the things not allowed for moderators, that we need to. So, can we already merge and later when the story is done, we can add more tests?
> apps/modules/predicates: refactor predicates

- adhocracy4/comments_async/serializers.py
- tests/comments/test_async_api.py
I didnt replace the now used comments_contenttype that is passed through template tags so far as I thought we can do that when we start working on the comments anyway? So for now, this is just extra..
> comments/serializers: add comment_content_type

- adhocracy4/emails/base.py
- adhocracy4/reports/emails.py
This even works locally. Because of hasattr, it also works with projects without a site added to the organisation.
I thought about also adding the organisation stuff to the attachments to display another logo for organisation emails like in a+, but as we do not have that in mB, but do have organisation logos there, I decided against that.
> apps/emails: add organsiation to get_site and report emails

- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/templatetags/react_comments_async.py
- adhocracy4/static/api.js
- package.json
- tests/comments/test_async_templatetags.py
There is still one axios call missing here: https://github.com/liqd/adhocracy4/blob/39acf0711aa7a614c596e2ee943f1528a8951ab7/adhocracy4/comments_async/static/comments_async/comment_box.jsx#L452
I wasnt sure how to handle it, because the url comes from pagination. I guess there are 2 options:
1. I could modify pagination that it doesnt return the url, but the page name and then pass that as data and use api.js
2. Or use fetch directly here if that is the long term plan anyway (is it? :))?
What do you think @khamui @phillimorland @fuzzylogic2000 ?
Update: as discussed I now use fetch directly for this.
> Ks 2022 02 use internal api to fetch comments

- adhocracy4/comments_async/static/comments_async/comment.jsx
it seems that currently only date in jsx is used in `comments_async`.
Not sure if sending two extra fields is the right way? I tried converting it on frontend
but that only works with locale set to 'de'.
fixes #918
> comments_async/date: using '<time>element'

- adhocracy4/api/permissions.py
We currently get a 500 for OPTIONS requests, see e.g. here https://sentry.liqd.net/organizations/liqd/issues/1939/?project=2
So we should either handle them or disallow them, but I guess its ok to allow them, especially since we still check permissions. 
See here for django restframework docs of OPTIONS request: https://www.django-rest-framework.org/api-guide/metadata/
> api/permissions: allow options requests in ViewSetRulesPermission

- adhocracy4/comments_async/serializers.py
will fix https://github.com/liqd/a4-meinberlin/issues/4256 once updated
@khamui Luckily someone already explained it in here: https://github.com/liqd/a4-meinberlin/blob/23922a3797db0e06b6de6cd1aa87bc73224cbc17/meinberlin/apps/contrib/templatetags/contrib_tags.py#L50
> apps/async_comments: make sure local time is used for comment dates

- adhocracy4/test/factories/__init__.py
- adhocracy4/test/factories/follows.py
- tests/follows/conftest.py
I don't know why I didn't do it like this in the first place. Now also works in again in projects that don't have the a4 follows installed (like opin).
> test/factories: move follow factory to own file

- requirements/base.txt
- see https://github.com/justinmayer/django-autoslug/issues/78
> deps: use own autoslug repo with fix for trailing dash

- adhocracy4/api/dates.py
- adhocracy4/comments_async/serializers.py
I moved the date conversion to a function, so we can use it in other places. I guess it would better fit into contrib, but we dont have that in a4, so left it in comments app for now.. could also create contrib folder?
> comments: move date conversion to own function and use in serializer

- adhocracy4/comments/models.py
Turns out that update_fields should be used to specify which model fields are saved, i.e. when specified only those fields will be saved. That is why when comment text was changed, nothing else was saved anymore (was also a problem for categories). 
So we will have to do it differently in KOSMO to detect if the comment text was changed. Following [this](https://stackoverflow.com/a/10299274), my idea would be to compare getattr(instance, '_former_comment') and getattr(instance, 'comment') [here](https://github.com/liqd/a4-kosmo/blob/main/apps/classifications/signals.py#L19) or alternatively make our own signal.. will do that tomorrow!
> comments/models: remove wrong usage of update fields

- adhocracy4/comments/models.py
- tests/comments/test_model.py
Had to change this again as need to update former_comment after saving :see_no_evil: 
The super.save() does not return anything, so fine to remove the return here, I think.
Used here: https://github.com/liqd/a4-kosmo/pull/268
> comments/models: update _former_comment after save

- adhocracy4/comments_async/serializers.py
- adhocracy4/comments_async/static/comments_async/comment_list.jsx
- tests/comments/test_async_api.py
So we can distinguish if a user image is actually present or not.. 
Unfortunately cant test the fallback_image here, as there is no user model in a4 (or is there a way @fuzzylogic2000 ?), so coverage decreases :neutral_face: But I will add a test in aplus!
> comments_async/serializers//static: serve fallback image in own field

- requirements/base.txt
bleach needs the tinecss2 library which was moved to the css extra - this was previously installed as dependency of easy-thumbnail but there it also moved into the extra svg. Install both explicitely
> requirements: include extras for Bleach and easy-thumbnail

- adhocracy4/dashboard/views.py
- tests/dashboard/test_blueprint_templates.py
- tests/dashboard/test_views.py
- tests/project/blueprints_with_type.py
Needed for external projects, bplans and project containers.
Kind of belongs to https://github.com/liqd/a4-meinberlin/pull/4449
> dashboard/views: add module type in ProjectCreateView

- adhocracy4/dashboard/__init__.py
- adhocracy4/dashboard/components/__init__.py
- tests/dashboard/test_project_dashboard.py
needed for https://github.com/liqd/a4-meinberlin/pull/4484
I thought about making more use of this also here and using it in https://github.com/liqd/adhocracy4/blob/04466cb3b14ca7a952c09e060a6c615c1c9173ae/adhocracy4/dashboard/templates/a4dashboard/base_dashboard_project.html#L27 
But adding all that complexity in a4, when we don't need it, did not make sense to me.
> apps/dashboard: add for_superuser property to module component menu

- .eslintrc
- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/static/comments/react_comments.jsx
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/static/comments_async/comment_category_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_list.jsx
- adhocracy4/comments_async/static/comments_async/index.jsx
- adhocracy4/follows/static/follows/react_follows.jsx
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon_with_preset.js
- adhocracy4/polls/assets/EditPollQuestions.jsx
- adhocracy4/polls/assets/PollQuestion.jsx
- adhocracy4/polls/assets/PollQuestions.jsx
- adhocracy4/polls/assets/react_polls.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/static/Alert.jsx
- package.json
This PR will make a4 unusable in all other projects!
> React 18: static/*: update render functions to react18 syntax

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_category_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_manage_dropdown.jsx
- adhocracy4/comments_async/static/modals/moderate_modal.jsx
- adhocracy4/polls/static/PollDashboard/EditPollOpenQuestion.jsx
- adhocracy4/polls/static/PollDashboard/EditPollQuestion.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/static/Alert.jsx
This will fix the issue with the disappearing translations. Template strings like `some string ${someVar}` will break our translations so we should avoid them
> replace template strings with regular string concat

- adhocracy4/projects/templatetags/project_tags.py
- tests/projects/test_project_templatetags.py
was moved to opin in https://github.com/liqd/a4-opin/pull/2592
> apps/projects: remove method from templatetag that was only used in opin

- adhocracy4/filters/rest_filters.py
We are already using the DefaultsRestFilterSet in mb, so I figured adding in a4 is better than in aplus. The DistinctOrderingFilter could also be reused I guess.
Once this is merged, will also change in mb to use it from a4.
> filters/rest_filters: add DefaultsRestFilterSet

- adhocracy4/projects/mixins.py
- adhocracy4/projects/models.py
- changelog/7428.md
Ok, this story is actually still in the backlog, was checking it together with @goapunk to see if is good for onboarding, but seemed a bit too complicated to find the right places.
But maybe @m4ra and @hklarnerliqd can review :) It needs another part in Aplus, will also tag you there!
> [7428] projects: add intial_slide to view context of module detail views

- adhocracy4/comments_async/api.py
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/models/query.py
- changelog/0004.md
- tests/comments/test_async_api.py
- tests/comments/test_async_api_org_terms.py
on state variables. Should fix the issue with the scrolling not working when an anchor is passed.
> comments_async: make fetchComments take arguments instead of relying

- .github/workflows/django.yml
It's quite slow and not super helpful, if we want the coverage in github we should probably find something else. We already removed it in the other projects
**Tasks**
> ci: remove frontend coverage test

- adhocracy4/dashboard/mixins.py
- changelog/_00010.md
- tests/actions/factories.py
DashboardComponentDeleteSignalMixin and add documentation.
**Tasks**
> dashboard/mixins: change form_valid back to delete in

- adhocracy4/dashboard/mixins.py
fixes `FAILED tests/maptopicprio/dashboard_components/test_views_module_maptopics.py::test_maptopic_delete_view - TypeError: __init__() got an unexpected keyword argument 'component'`
**Tasks**
> dashboard/mixins.py: add missing args and kwargs

- adhocracy4/comments_async/static/comments_async/comment_form.jsx
**Description**
Capitalize buttons copy on comments app
not sure this need changelog
**Tasks**
> comments_async/comment_form.jsx: capitalize buttons cta

- adhocracy4/maps_react/static/a4maps_react/Map.jsx
- adhocracy4/maps_react/static/a4maps_react/__tests__/Map.jest.jsx
callback to be executed before the map object is created. Instead of relying on the refs, use the useMap hook and conditional rendering for the polygon.
Not sure if this is the best approach but for now it makes the maps work again on design-dev
fixes https://github.com/liqd/a4-meinberlin/issues/5582
to reproduce the error add the following to your `webpack.dev.js`:
```
module.exports = merge(common, {
devtool: 'eval-source-map',
optimization: {
'nodeEnv': 'production'
}                                    
})                                                                          
```
and try to create a mapidea or proposal
**Tasks**
> maps_react: fix indetermined execution order causing the polygon

- adhocracy4/categories/forms.py
- changelog/_1111.md
- tests/categories/conftest.py
- tests/categories/test_form.py
- tests/project/settings.py
make icon form field optional  to allow categories without icon
fixes https://github.com/liqd/adhocracy-plus/issues/2580 and the same issue in mb
**Tasks**
> categories: make icon form field optional 

- adhocracy4/static/Modal.jsx
fixes https://github.com/liqd/adhocracy4/issues/1588 & https://github.com/liqd/adhocracy-plus/issues/2565
Fix undefined props error in button functionality and replace handleClose method with Bootstrap's `data-bs-dismiss` for modal closing
> static/Modal.jsx: fix modal not closing on comment deletion

- adhocracy4/modules/models.py
- changelog/_1112.md
- tests/modules/test_module_models.py
> modules: add missing get_blueprint_type_display method

- adhocracy4/polls/static/PollDetail/PollOpenQuestion.jsx
- adhocracy4/polls/static/PollDetail/PollQuestion.jsx
- adhocracy4/polls/static/PollDetail/PollResults.jsx
- adhocracy4/polls/static/__tests__/__snapshots__/PollQuestion.jest.jsx.snap
- changelog/_8186.md
It's a dependency of https://github.com/liqd/a4-meinberlin/pull/5630
**Tasks**
> [#8161] mB poll redesign

- adhocracy4/comments_async/static/comments_async/__tests__/__snapshots__/comment_box.jest.jsx.snap
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
fixes : https://github.com/liqd/adhocracy4/issues/1043
steps to reproduce: https://github.com/liqd/adhocracy4/issues/1043#issuecomment-2301842120
> comments_async: display correct message for private group users

- adhocracy4/comments_async/static/comments_async/__tests__/__snapshots__/comment.jest.jsx.snap
- adhocracy4/comments_async/static/comments_async/__tests__/__snapshots__/comment_box.jest.jsx.snap
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_list.jsx
- adhocracy4/comments_async/static/comments_async/comment_manage_dropdown.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
dependencies:
https://github.com/liqd/a4-meinberlin/pull/5686
https://github.com/liqd/adhocracy-plus/pull/2747
**Tasks**
> [#7864] comments and ratings: small changes following mB redesign

- Makefile
Makefile command was broken, this fixes it.
**Tasks**
> Makefile: fix broken pytest-lastfailed

- adhocracy4/static/Captcha.jsx
the text mode from not showing due to the styling for the plain js captcha.
to be tested with https://github.com/liqd/adhocracy-plus/pull/2841
**Tasks**
> static/Captcha: add react specific classes to some fields to prevent

- adhocracy4/polls/serializers.py
- adhocracy4/polls/static/PollDashboard/EditPollManagement.jsx
- adhocracy4/polls/static/react_poll_management.jsx
- adhocracy4/polls/templatetags/react_polls.py
- changelog/8381.md
voting
- add missing changelog
required to e.g. disable it in meinBerlin for now (or other forks of a+)
**Tasks**
> polls: add new django setting to enable or disable the unregistered poll

- adhocracy4/polls/api.py
- adhocracy4/polls/signals.py
- changelog/8381.md
- tests/polls/test_vote_api.py
> polls: add new signal which is called after a user voted on a poll

- CHANGELOG.md
- changelog/1428.md
- changelog/1461.md
- changelog/1491.md
- changelog/1523.md
- changelog/284.md
- changelog/7619.md
- changelog/8372.md
- changelog/8381.md
- changelog/8447.md
- changelog/8462.md
- changelog/8483.md
- changelog/8529.md
- changelog/994.md
- changelog/_1112.md
- changelog/_8186.md
> [8450] release mb-2412.1

- adhocracy4/emails/mixins.py
- changelog/8527.md
Add new setting `A4_EMAIL_ATTACHMENTS` for when you need more than the `email_logo.png` attachment in your emails.
No breaking change as a fallback is included when the setting is not existing.
See https://github.com/liqd/a4-meinberlin/pull/5908 for usage
**Tasks**
> [#8527] E-Mail attachment setting

- adhocracy4/maps_react/static/a4maps_react/AddressSearch.jsx
- adhocracy4/maps_react/static/a4maps_react/ControlWrapper.js
- adhocracy4/static/classNames.js
- adhocracy4/static/forms/AutoComplete.jsx
- adhocracy4/static/forms/__tests__/AutoComplete.jest.jsx
- adhocracy4/static/forms/__tests__/useCombobox.jest.js
- adhocracy4/static/forms/useCombobox.js
- adhocracy4/static/useDebounce.js
- index.js
This is part 1 of 2. Please feel already free to review and merge this. This will be merged into another branch that stems from `main` and so will part 2. Doing it like this allows me to split this story up for easier review into...
1. Moving components around (from mb -> a4)
2. Making further code changes in these components to fulfil the user story.
Once both parts are reviewed & merged into this branch `pv-2025-01-address-search` I can then merge this into `dev` (mb)/`main` (a4)
**Describe your changes**
Moves components out of mein berlin and into a4, adapts code to be more generic. It moves over:
1. The useCombobox hook, that is used in a) AutoComplete (AddressSearch) and b) Multi-Select
2. the useDebounce hook which is used to create debounced callbacks that you can put on e.g. a …
> [#8639] address-search: move components into a4 from mein_berlin PT 1

- adhocracy4/maps_react/templatetags/react_maps_tags.py
- adhocracy4/maps_react/widgets.py
- tests/maps_react/test_templatetags.py
- tests/maps_react/test_widget.py
fixes map namespace clash with react_maps
mb PR: https://github.com/liqd/a4-meinberlin/pull/6003
**Tasks**
> maps/react: fix react map namespaces

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments_async/static/comments_async/__tests__/__snapshots__/comment.jest.jsx.snap
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_manage_dropdown.jsx
- adhocracy4/comments_async/static/modals/UrlModal.jsx
- adhocracy4/reports/static/reports/ReportModal.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/reports/templatetags/react_reports.py
- adhocracy4/static/Modal.jsx
- changelog/_0003.md
- tests/reports/test_report_templatetags.py
**_please dont merge this once approved, waiting to touch a-plus first_**
Replace Bootstrap modals with native HTML <dialog> element  and update styles for the mB redesign.
This change simplifies our modal implementation while improving the mobile experience. The <dialog> element provides better accessibility and native support for modal behaviors.
https://github.com/user-attachments/assets/3fb8d9a0-9e58-4510-b780-dc92d0c98ef7
https://github.com/user-attachments/assets/0215e666-2eab-40f6-9323-e0f9f697e734
TODO:
> static/Modal.jsx refactor: migrate from Bootstrap to native dialog element adapt to mB redesign

- adhocracy4/projects/models.py
added because of  https://github.com/liqd/a4-meinberlin/pull/6030
> projects: add contact details flag to ProjectContactDetailMixin

- adhocracy4/comments_async/static/modals/UrlModal.jsx
fixes https://github.com/liqd/a4-meinberlin/issues/6062
> issue fix - modals/UrlModal: reset clicked state on close

- adhocracy4/maps/mixins.py
- changelog/_0004.md
- tests/maps/test_map_mixins.py
fixes https://github.com/liqd/a4-meinberlin/issues/6150
**Tasks**
> maps: fix GeoJsonPointMixin with dict as input

- adhocracy4/follows/static/follows/FollowButton.jsx
- adhocracy4/follows/static/follows/__tests__/FollowButton.jest.jsx
- adhocracy4/follows/templatetags/react_follows.py
- changelog/_0005.md
**Description**
Refactor FollowButton to allow for alerts outside the container
> follows: refactor FollowButton.js

- adhocracy4/comments_async/static/comments_async/__tests__/__snapshots__/comment.jest.jsx.snap
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_manage_dropdown.jsx
This moves the report and share button of comments into the dot-menu/dropdown.
For more information, see this discussion https://github.com/liqd/a4-meinberlin/issues/6279
**Tasks**
> comments: move report and share into dropdown
