- .gitignore
- MANIFEST.in
- adhocracy4/images/apps.py
- adhocracy4/images/fields.py
- adhocracy4/images/forms.py
- adhocracy4/images/static/a4images/imageUploader.js
- adhocracy4/images/templates/a4images/image_upload_widget.html
- adhocracy4/images/validators.py
- adhocracy4/images/widgets.py
- adhocracy4/projects/migrations/0001_initial.py
- adhocracy4/projects/migrations/0002_change_to_configured_image_field.py
- adhocracy4/projects/models.py
- package.json
- setup.py
- tests/images/test_image_validations.py
- tests/images/test_image_widgets.py
- tests/project/settings.py
- reads image properties from settings
- setups validators accordingly
- generates help texts automatically
- setup our own upload widget
> Write custom image field

- adhocracy4/generics.py
- adhocracy4/ratings/apps.py
- adhocracy4/ratings/signals.py
- tests/apps/questions/apps.py
- tests/apps/questions/phases.py
- tests/project/settings.py
- tests/projects/test_mixins.py
- tests/ratings/test_rating_signals.py
- introduce reusable generic signal setup
- ensure that ratings are deleted if content object is deleted
> Move signal setup to generics module

- package.json
I copied all dependencies that are actually used from euth-wagtail
> declare js dependencies

- adhocracy4/comments/apps.py
- adhocracy4/reports/apps.py
- tests/project/settings.py
Requires adjustment in the project settings.
> Use plural in configs (breaking)

- adhocracy4/contrib/views.py
- tests/contrib/test_views.py
see https://docs.djangoproject.com/en/1.10/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.get_ordering
> implement SortableListView.get_ordering()

- adhocracy4/categories/admin.py
- adhocracy4/categories/apps.py
- adhocracy4/categories/models.py
- tests/conftest.py
- tests/project/settings.py
Add the following models:
- `Category`: categories that belong to a module.
- `Categorizable`: Add a category field to another model, e.g. Item
> Categories app

- adhocracy4/categories/forms.py
- adhocracy4/contrib/apps.py
- adhocracy4/filters/views.py
- adhocracy4/modules/admin.py
- adhocracy4/modules/predicates.py
- adhocracy4/modules/views.py
- adhocracy4/projects/mixins.py
- adhocracy4/rules/mixins.py
- tests/apps/questions/migrations/0002_question_category.py
- tests/apps/questions/models.py
- tests/apps/questions/views.py
Add different item features/extensions
> Generic item features

- docs/phases.md
In this pull request:
- document the original modelling/constraints of phases
- describe what has bee implemented
- list upcoming challenges
In **future** pull requests:
- combine plan and current state into a short term vision / documentation of desired model
- create a long term vision from challenges, further discussion and product vision workshop
> Document the current phase model

- adhocracy4/comments/static/comments/Comment.jsx
see https://github.com/liqd/a4-meinberlin/pull/113
> mark comment author links as external for embed

- .editorconfig
- .eslintrc
- .polylintrc
- Makefile
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments/static/comments/CommentReplyBar.jsx
- adhocracy4/reports/emails.py
- adhocracy4/static/Modal.jsx
- package.json
Fixes #33
I also added polylint to speed up the commit hook.
The switch from alignment to indentation in JSX might be controversial, but
this is what eslint thinks is right.
> Add eslint

- MANIFEST.in
> Fix packing of reports app

- MANIFEST.in
Since this is already the second PR with that change and it seems that we will add more and more templates or static content we should address this more broadly.
I tried already to add all template directories and static dir to the package, but failed :sob:. Maybe someone can assist me while I start another attempt?
> Add maps templates and static content to pypackage

- adhocracy4/maps/models.py
- adhocracy4/modules/models.py
The method should be static since it doesn't require an instance to function.
> make modulesettings.widgets a staticmethod

- adhocracy4/api/permissions.py
- adhocracy4/comments/api.py
- adhocracy4/comments/rules.py
- adhocracy4/ratings/api.py
- adhocracy4/ratings/rules.py
- tests/apps/questions/phases.py
- tests/apps/questions/rules.py
- tests/comments/test_api.py
- tests/helpers.py
- tests/ratings/test_rating_api.py
Fixes #31 
- add rules for comments and rates
- enforce those rules from the api classes
> Add rules to REST api

- adhocracy4/api/mixins.py
- adhocracy4/api/routers.py
Adds a router to include the module in an API URL.
Needed to check document permissions.
> API module router and view

- adhocracy4/filters/filters.py
- tests/filter/test_filter_views.py
Copy from https://github.com/liqd/a4-opin/commit/c9a12dc9851f35ecec39a7950eeb1552c81a7fe9
> Allow default filter values

- adhocracy4/projects/models.py
* return whether a project is archivable
* a project is archivable if not yet archived and if already finished
> return whether a project can be archived

- adhocracy4/api/mixins.py
- adhocracy4/api/routers.py
For organisation based permission checks (e.g. project creation)
> Add organisation api router and mixin

- adhocracy4/images/validators.py
- don't display bytes as megabytes
> Fix image size validation error message

- adhocracy4/images/static/a4images/imageUploader.js
- adhocracy4/maps/static/a4maps/map_choose_point.js
- adhocracy4/maps/static/a4maps/map_choose_polygon.js
- adhocracy4/maps/static/a4maps/map_display_point.js
- adhocracy4/maps/static/a4maps/map_display_points.js
- adhocracy4/static/api.js
see https://github.com/liqd/a4-meinberlin/pull/279
> use a4.embed.ready event

- adhocracy4/images/fields.py
for some reason this needs to be lazy
> fix image help_text translation

- adhocracy4/phases/migrations/0005_add_verbose_names.py
- adhocracy4/phases/models.py
- adhocracy4/projects/migrations/0007_add_verbose_names.py
- adhocracy4/projects/models.py
I had to switch to `ugettext_lazy` in one place. I am not completely sure about the consequences though.
> add some translatable verbose_names

- adhocracy4/actions/admin.py
- adhocracy4/comments/admin.py
- adhocracy4/follows/admin.py
- adhocracy4/modules/admin.py
- adhocracy4/ratings/admin.py
- adhocracy4/reports/admin.py
> Make creators readonly in django admin

- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- package.json
Nothing much has happend. This is just to stay up-to-date.
> update npm dev dependencies

- adhocracy4/projects/migrations/0008_project_tile_image.py
- adhocracy4/projects/models.py
- adhocracy4/projects/signals.py
- tests/project/settings.py
The aspects of the tile image and the heroimage is too different. Cropping the heroimage to the tile does not work in general.
> add tile image to project

- adhocracy4/actions/admin.py
> Fixup for action django admin

- adhocracy4/projects/models.py
This simply adds a new last_active_module property which returns the active phases module, or if non is active the last active phases module
> Add last_active_module property to projects

- Makefile
> Fix install target in Makefile

- package.json
these resulted from a merge error in 0b86d12fe35eb7a18c6ecdcb77462eaa63e5b164
> rm duplicated dependencies in package.json

- adhocracy4/static/Modal.jsx
> set initial aria-hidden on modals

- adhocracy4/filters/templates/a4filters/widgets/free_text_filter.html
- tests/filter/test_filter_widgets.py
just some small usability improvements
> refactor default free text filter template

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/static/comments/CommentList.jsx
- adhocracy4/follows/static/follows/FollowButton.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/reports/static/reports/ReportModal.jsx
- adhocracy4/static/Modal.jsx
`React.createClass` is deprecated. This PR uses functional components and ES6 class syntax instead.
> avoid React.createClass

- README
- README.md
We need this in order to receive the open source plan from browserstack.
> add link to browserstack

- adhocracy4/comments/models.py
- adhocracy4/comments/static/comments/Comment.jsx
> small comment changes

- adhocracy4/comments/static/comments/Comment.jsx
I don't think showing the last modified date makes sense for a deleted comment.
> show [creation] date on deleted comments

- .travis.yml
- set same python version as on target servers
- fail checks if there are missing migrations
> Improve traivs config

- adhocracy4/maps/static/a4maps/map_choose_point.js
This function was introduced in 59b6f46.
I missed the fact that this file is not processed by webpack/babel, so we can not use ES6 here.
> avoid ES6 in map code

- adhocracy4/comments/static/comments/CommentEditForm.jsx
regression that was introduced in 425be59a
> Fix comment editing

- package.json
most notably update jquery to 3.x.x (see https://jquery.com/upgrade-guide/3.0/)
I did *not* update react to 16.x.x yet.
> update npm depedencies

- adhocracy4/test/factories/__init__.py
- requirements/base.txt
- change project information fake data to text because paragraphs
produces a list of strings, which is not well liked by the new
bleach version
> Update bleach to newest version

- adhocracy4/categories/admin.py
- adhocracy4/comments/admin.py
- adhocracy4/follows/admin.py
- adhocracy4/maps/admin.py
- adhocracy4/modules/admin.py
- adhocracy4/projects/admin.py
- adhocracy4/ratings/admin.py
- adhocracy4/reports/admin.py
- define a project filter that depends on organisation and is_archived
- extend the admin views of all apps with additional information and filters
> Extend django admin views

- CHANGES
- adhocracy4/comments/static/comments/react_comments.jsx
- adhocracy4/comments/templatetags/react_comments.py
- adhocracy4/follows/static/follows/react_follows.jsx
- adhocracy4/follows/templatetags/react_follows.py
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/ratings/templatetags/react_ratings.py
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/reports/templatetags/react_reports.py
- tests/comments/test_templatetags.py
- tests/ratings/test_rating_templatetags.py
- tests/reports/test_report_templatetags.py
another step towards a content security policy.
You need to initialise the react components yourself. See https://github.com/liqd/a4-opin/pull/775 for an existing implementation in opin.
> avoid using inline script

- adhocracy4/maps/static/a4maps/map_choose_polygon.js
see https://github.com/liqd/a4-meinberlin/issues/1028
> disable circlemarker in leaflet draw

- adhocracy4/forms/widgets.py
- adhocracy4/images/widgets.py
- adhocracy4/maps/widgets.py
- calls are executed during initalisation, which breaks the manifest file store
> Remove redudant calls to staticfiles_storage

- adhocracy4/comments/static/comments/CommentEditForm.jsx
fixes https://github.com/liqd/a4-product/issues/112
> fix comment edit buttons

- package.json
I think we can do this now. Mein berlin seemed to be ready long ago I just updated advocate-europe and opin to react16 as well.
> Update react to version 16

- docs/testing.md
> some first thoughts about testing

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- add class for better styling
- make labeling of "show more comments" more intuitive
- set focus on lciking "anwser" button
> Improve comment anwser button

- adhocracy4/reports/templates/a4reports/emails/report_creator.en.email
- fix typos
- fix template filter formarting
- lowercase all verbose names
> Improve the report notification text

- CHANGES
- adhocracy4/filters/filters.py
we need it because https://github.com/carltongibson/django-filter/issues/862
> move the distinct ordering filter to a4

- CHANGES
- adhocracy4/static/api.js
required by https://github.com/liqd/a4-meinberlin/pull/1215/
> adding API queries for moderatorremark

- adhocracy4/maps/static/a4maps/map_display_points.js
changes needed to 
- not show image when no image is given
- use flexbox to show image to the right of popup
this should not affect the styling in other projects
> add a wrapping div and an extra css class

- adhocracy4/polls/static/polls/PollManagement.jsx
- adhocracy4/polls/static/polls/QuestionForm.jsx
The paragraph tag was used for styling the following element so I decided to just give it a class name rather than adding more divs to both elements.
Added container div around container for positioning purposes.
Also just realised that where I added Answer label will probably need additional stuff which I forgot
> addition of class names and container div for poll styling

- adhocracy4/dashboard/templates/a4dashboard/project_list.html
- adhocracy4/forms/templates/a4forms/includes/inline_form.html
- adhocracy4/images/templates/a4images/image_upload_widget.html
- adhocracy4/maps/static/a4maps/map_display_points.js
- adhocracy4/polls/static/polls/QuestionForm.jsx
There is already a PR (https://github.com/liqd/a4-meinberlin/pull/1243) in meinBerlin using the new fontawesome. But before merging, we need to also update the other projects.
> update fontawesome - use new classnames

- adhocracy4/dashboard/templates/a4dashboard/includes/progress.html
> Pm 2018 10 depublication btn

- adhocracy4/categories/filters.py
- adhocracy4/dashboard/templates/a4dashboard/blueprint_list.html
- adhocracy4/dashboard/templates/a4dashboard/project_list.html
- adhocracy4/static/select_dropdown.js
> Pm 2018 10 alt attr

- adhocracy4/comments/models.py
- adhocracy4/comments/static/comments/Comment.jsx
An experimental solution for https://taiga.liqd.net/project/ggr-spd/us/47
Todo:
- partly pull in react code from https://github.com/liqd/a4-spd/pull/531 to show a share button and visual highlighting
> link to individual comments

- adhocracy4/comments/models.py
Fixes https://github.com/liqd/a4-spd/issues/580
> comments: Fix get_absolute_url for nested comments

- adhocracy4/modules/models.py
I solved it a bit differently from the stuff in the projects. The
projects rely on the phases being started/running/whatever. This will
become confusing once we have more than one phase in a module and there
is time between the phases. A module is also running between its phases.
> modules: add properties for end, start and status

- adhocracy4/projects/mixins.py
Well, It's working.
But apart from the tests, there is some kind of explanation how to use the three new mixins missing...
> projects/mixins: add projectModuleDispatchMixin

- adhocracy4/projects/mixins.py
- adhocracy4/projects/models.py
I fixed the index in a very wrong place before...
> projects and modules: fix index for module clusters

- Makefile
A proper `clean` is sometimes necessary.
> Makefile: Add 'clean' and phony entries

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/polls/static/polls/Question.jsx
This seems to fix the last ones
> Pm 2019 09 trans fix 2

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/polls/static/polls/Question.jsx
ones I missed in previous pull requests
> trans: move varibles outside component

- adhocracy4/maps/static/a4maps/a4maps_choose_point.js
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/maps/static/a4maps/a4maps_display_point.js
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
This was simply wrong and required us to work around it in webpack.
> maps/static: Properly import locally

- adhocracy4/comments_async/static/comments/comment_form.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_form.jsx
> comments_async/static: Fix imports

- adhocracy4/dashboard/mixins.py
fixes https://github.com/liqd/adhocracy-plus/issues/114
> dashboard/mixin: Add org slug if needed

- adhocracy4/comments_async/api.py
> comments_async/api: Replace firstname by username

- adhocracy4/forms/templates/a4forms/multiple_input.html
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
fixes #351
and fixes a+ issue https://github.com/liqd/adhocracy-plus/issues/108
> Pm 2019 12 issue fixes

- adhocracy4/comments/static/comments/Comment.jsx
- adhocracy4/comments/static/comments/CommentBox.jsx
- adhocracy4/comments/static/comments/CommentEditForm.jsx
- adhocracy4/comments/static/comments/CommentForm.jsx
- adhocracy4/comments/static/comments/CommentList.jsx
- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments/static/comments/react_comments.jsx
- adhocracy4/comments_async/static/comments/comment.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment.jsx
- adhocracy4/comments_async/static/modals/modal.jsx
- adhocracy4/dashboard/assets/dashboard.js
- adhocracy4/follows/static/follows/react_follows.jsx
- adhocracy4/maps/static/a4maps/a4maps_choose_point.js
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/maps/static/a4maps/a4maps_common.js
- adhocracy4/maps/static/a4maps/a4maps_display_point.js
- adhocracy4/maps/static/a4maps/a4maps_display_points.js
- adhocracy4/polls/static/polls/ChoiceForm.jsx
- adhocracy4/polls/static/polls/PollManagement.jsx
- adhocracy4/polls/static/polls/Question.jsx
- adhocracy4/polls/static/polls/QuestionForm.jsx
- adhocracy4/polls/static/polls/react_polls.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/reports/static/reports/ReportModal.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/static/Alert.jsx
- adhocracy4/static/ErrorList.jsx
- adhocracy4/static/Modal.jsx
- adhocracy4/static/config.js
This was necessary after recent eslint updates
> assets: linting fixes

- adhocracy4/comments_async/static/comments/comment_box.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_box.jsx
linting errors from linter update, to be re-based after https://github.com/liqd/adhocracy4/pull/450
> Pm 2020 01 debate struct

- adhocracy4/comments_async/static/comments_with_categories/comment.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_box.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_form.jsx
there is a corresponding a+ pull request https://github.com/liqd/adhocracy-plus/pull/227
> Pm 2020 01 child comment answer

- adhocracy4/comments_async/api.py
- adhocracy4/comments_async/serializers.py
- tests/comments/test_async_api.py
- tests/project/urls.py
On the way, fix a potential crash and a deprecation warning
> comments_async: Add tests

- adhocracy4/comments_async/serializers.py
- adhocracy4/comments_async/static/comments_with_categories/comment.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_box.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_form.jsx
- adhocracy4/comments_async/static/comments_with_categories/comment_list.jsx
- adhocracy4/comments_async/static/modals/modal.jsx
- adhocracy4/comments_async/static/modals/url_modal.jsx
fixes https://github.com/liqd/adhocracy-plus/issues/273
fixes https://github.com/liqd/adhocracy-plus/issues/279
fixes https://github.com/liqd/adhocracy-plus/issues/275
fixes https://github.com/liqd/adhocracy-plus/issues/271
> Pm 2020 02 issues with comments

- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_category_edit_form.jsx
fixes editing on async comments - not the most elegant solution but it works! :)
> comments_async/commnet_edit_form: adding category check to edit form

- package.json
Reverts liqd/adhocracy4#522 to fix dropdowns until bootstrap or jquery release the fix
> Revert "fix(deps): update dependency jquery to v3.5.0"

- adhocracy4/phases/models.py
- docs/datamodel.md
- docs/development.md
- docs/phases_and_modules.md
- docs/timeline.md
@fuzzylogic2000 and this is a4 stuff, I have undone most of my changes about weight stuff and just added little sentance about modules
> docs/datamodel: english tweeks, strike throughs and adding small updates

- docs/dashboard.md
- docs/roles_and_permissions.md
There is certainly more that should be said, but this is a start...
> Ka 2020 08 more docs

- adhocracy4/projects/models.py
- tests/projects/test_project_model_phase_properties.py
fixes https://sentry.liqd.net/sentry/meinberlin-prod/issues/1144/
> apps/projects: make sure time_left is returned also below 1 minute

- adhocracy4/dashboard/forms.py
- adhocracy4/phases/admin.py
- adhocracy4/phases/forms.py
- adhocracy4/phases/models.py
- adhocracy4/test/factories/__init__.py
- tests/dashboard/components/test_views_module_area_settings.py
- tests/dashboard/components/test_views_module_basic.py
- tests/dashboard/components/test_views_module_phases.py
- tests/dashboard/components/test_views_project_basic.py
- tests/dashboard/components/test_views_project_information.py
- tests/dashboard/components/test_views_project_result.py
- tests/helpers.py
- tests/phases/test_phase_predicates.py
- tests/project/blueprints.py
That took a while! But is done now. And of course I found an error when I added the tests... But all should be fine now. You should be able to test with any project.
> apps/dashboard: validate that phases of the same module don't overlap

- adhocracy4/actions/models.py
- adhocracy4/dashboard/forms.py
- adhocracy4/projects/enums.py
- adhocracy4/projects/migrations/0028_project_access.py
- adhocracy4/projects/migrations/0029_is_public_to_access.py
- adhocracy4/projects/models.py
- adhocracy4/test/factories/__init__.py
- tests/actions/test_models.py
- tests/dashboard/components/test_views_project_basic.py
- tests/modules/test_module_predicates.py
- tests/phases/test_phase_predicates.py
- tests/polls/test_vote_api.py
- tests/projects/test_project_models.py
- tests/projects/test_project_predicates.py
- tests/projects/test_project_templatetags.py
- tests/projects/test_project_views.py
To structure things a bit more
> projects: Move Access enum into its own file

- adhocracy4/projects/enums.py
- adhocracy4/projects/migrations/0028_project_access.py
- adhocracy4/projects/migrations/0029_is_public_to_access.py
Changed order of acces enum values and adjusted migrations.
> Ks 2020 11 alter public to access migrations

- adhocracy4/projects/mixins.py
fixes https://sentry.liqd.net/sentry/aplus-prod/issues/1068/ and https://sentry.liqd.net/sentry/meinberlin-prod/issues/870/
fixes #592
> apps/projects/mixins: add some error handling for initial slide

- adhocracy4/comments_async/static/comments_async/comment_box.jsx
> comments_async: Hide filters there are no comments

- adhocracy4/comments_async/static/comments_async/comment.jsx
- package.json
This makes us render comments similar to what e.g. github does.
See https://github.com/remarkjs/react-markdown
Closes #629
> comments_async: Support markdown in comments

- adhocracy4/comments_async/static/comments_async/comment.jsx
Some more drive-by stuff - needs design/ux approval :)
Closes https://github.com/liqd/adhocracy-plus/issues/958
Pic1:
Pic2:
Pic3:
> comments_async: Show number of replies to comment (if applicable)

- adhocracy4/projects/utils.py
Attempt to fix https://github.com/liqd/adhocracy4/issues/644
> projects/utils: order projects also by weight to make it distinct

- adhocracy4/filters/filters.py
This allows us to have random but distinct ordering. The resulting
order will stay the same as long as the input queryset and the
`random_seed` argument stay the same. The seed AFAIK can have any
format - one example would be `datetime.date.today`.
Required for https://github.com/liqd/a4-civic-europe/pull/275
> filters: Add reproducable random case to DistinctOrderingFilter

- adhocracy4/filters/filters.py
- tests/filter/test_distinct_random_filter.py
> filters: Some improvements to distinct random ordering filter

- adhocracy4/comments_async/static/comments_async/comment_box.jsx
See https://web.dev/uses-passive-event-listeners/
> comments/assets: Use passive scroll listener

- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_list.jsx
Passing isReadOnly and isContextMember to child component `comment.jsx`.
Adding isAuthenticated flag to condition inside of `comment_form.jsx`.
fixes  #678
> Fixing bug in nested comment form

- docs/development.md
This was unclear for people new to the project and environment and meant commiting was made more difficult as our precommit relys on virenv checks so thought would be good to add
> update docs to include virtual env

- adhocracy4/comments_async/static/comments_async/comment_form.jsx
restoring logic of a merged PR (#705).
> Kt 2021 04 nested comment form

- adhocracy4/filters/filters.py
- tests/filter/conftest.py
- tests/filter/test_distinct_random_filter.py
Sorry, very non-creative with new class name in the end
> filters: move daily random to new filter class

- tests/polls/conftest.py
- tests/polls/factories.py
- tests/polls/test_models.py
@Rineee There will be more to add after the QS stuff, but let's merge and add that with that?!
> tests/polls: add tests for the new model fields

- adhocracy4/polls/models.py
- adhocracy4/polls/serializers.py
- tests/polls/test_template_tags.py
After all, it was much easier than I tried before..
> polls/serializers: annotate questions in poll serializer

- adhocracy4/polls/assets/PollQuestion.jsx
- adhocracy4/polls/assets/PollQuestions.jsx
- adhocracy4/polls/assets/react_polls.jsx
- adhocracy4/static/api.js
this is a wip. But in order to progress, it can be merged
> apps/polls/userview: polls questions logic etc.

- adhocracy4/ckeditor/templates/a4ckeditor/collapsible_fragment.html
- adhocracy4/comments/static/comments/CommentManageDropdown.jsx
- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_manage_dropdown.jsx
- adhocracy4/comments_async/static/modals/url_modal.jsx
- adhocracy4/filters/templates/a4filters/widgets/dropdown_link.html
- adhocracy4/maps/static/a4maps/a4maps_choose_polygon.js
- adhocracy4/polls/assets/PollQuestions.jsx
- adhocracy4/polls/assets/PollResults.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
- adhocracy4/static/select_dropdown.js
- package.json
> Pm 2021 07 show results

- adhocracy4/polls/assets/PollOpenQuestion.jsx
- adhocracy4/polls/assets/PollQuestion.jsx
- adhocracy4/polls/assets/PollQuestions.jsx
still to do (stole this from philli :)):
> apps/poll/userview: pollquestions show result & pollopenquestion

- adhocracy4/polls/assets/EditPollChoice.jsx
- adhocracy4/polls/assets/EditPollOpenQuestion.jsx
- adhocracy4/polls/assets/EditPollQuestion.jsx
- adhocracy4/polls/assets/EditPollQuestions.jsx
> apps/poll/editview: renaming to BEM convention

- adhocracy4/polls/assets/PollQuestions.jsx
- adhocracy4/polls/assets/PollResults.jsx
> Pm 2021 07 results improvments

- adhocracy4/polls/api.py
- adhocracy4/polls/assets/PollResults.jsx
- tests/polls/test_vote_api.py
This still doesnt catch the validation errors, but maybe we could merge this first, so Caro can test properly?
> polls/api: only save answer and other choice answer if not empty

- adhocracy4/polls/assets/PollResults.jsx
> apps/poll/pollresults: highlight users answer if exists

- adhocracy4/polls/api.py
- adhocracy4/polls/validators.py
- tests/polls/test_validators.py
- tests/polls/test_vote_api.py
Ok, I hope this is catching everything...
> Ks 2021 07 handle vote errors

- adhocracy4/polls/assets/PollQuestions.jsx
if no changes/modification on votes
issue reported in OPIN:
https://github.com/liqd/a4-opin/issues/2245
> apps/poll/userview: fix infinite loading spinner and show success alert

- adhocracy4/polls/assets/PollOpenQuestion.jsx
- adhocracy4/polls/assets/PollQuestion.jsx
fixes https://github.com/liqd/a4-opin/issues/2246
> polls/assets: disable inputs if phase not active

- adhocracy4/polls/assets/PollQuestions.jsx
should fix issue in meinberlin:
https://github.com/liqd/a4-meinberlin/issues/3789
closes liqd/a4-meinberlin#3789
> polls/save: disable button if no changes made yet

- adhocracy4/polls/models.py
fixing bug described in mein Berlin issue:
https://github.com/liqd/a4-meinberlin/issues/3692
closes liqd/a4-meinberlin#3692
> report/email: getting link from module

- package.json
> Revert "fix(deps): update dependency remark-gfm to v2"

- adhocracy4/test/helpers.py
This method serves to replace a project test method and is thus related to PR https://github.com/liqd/adhocracy-plus/pull/1432
> tests: added project method to a4 for general replacement

- tests/dashboard/components/test_views_module_area_settings.py
- tests/dashboard/components/test_views_module_basic.py
- tests/dashboard/components/test_views_module_phases.py
- tests/dashboard/components/test_views_project_basic.py
- tests/dashboard/components/test_views_project_information.py
- tests/dashboard/components/test_views_project_result.py
- tests/dashboard/test_dashboard_components.py
- tests/dashboard/test_views.py
- tests/modules/test_module_views.py
- tests/polls/dashboard_components/test_views_module_polls.py
- tests/polls/test_views_integration.py
- tests/projects/test_project_views.py
These changes in response to https://github.com/liqd/adhocracy4/pull/837#pullrequestreview-752405254.
Is this what you meant @fuzzylogic2000 or do you think that there are tests that are entirely missing that need to be written with the method? If so, could you point me in the right direction? Now looking into meinBerlin tests!
> tests: replaced 200 response code with new method

- adhocracy4/images/validators.py
You can test this directly using the ideas API in a+ and add an image there (/api/modules/<module_pk>/ideas).
> apps/images: make sure validation also works for APIs

- adhocracy4/polls/assets/PollOpenQuestion.jsx
- adhocracy4/polls/assets/PollQuestion.jsx
- adhocracy4/polls/assets/PollQuestions.jsx
- adhocracy4/polls/assets/PollResults.jsx
- adhocracy4/polls/serializers.py
fixes https://github.com/liqd/a4-meinberlin/issues/3867
fixes https://github.com/liqd/a4-meinberlin/issues/3787
> poll issue fixing

- .eslintrc
- .github/workflows/django.yml
- .gitignore
- Makefile
- __mocks__/djangoMock.js
- adhocracy4/polls/assets/__tests__/CharCounter.jest.jsx
- adhocracy4/polls/assets/__tests__/PollQuestion.jest.jsx
- adhocracy4/polls/assets/__tests__/__snapshots__/CharCounter.jest.jsx.snap
- adhocracy4/polls/assets/__tests__/__snapshots__/PollQuestion.jest.jsx.snap
- adhocracy4/polls/assets/__tests__/__testdata__/QUESTION_OBJECT.js
- babel.config.js
- jest.config.js
- package.json
Does it make sense in a4?
Maybe more than in aplus (or any other projects).
There is a general dilemma (in my head). We have components in a4 and in projects.
But where should we run the tests?
I didn't manage to run jest snapshots in aplus, but also make it run tests of the node_module dependency in a4.
So for now this commit just runs snapshot tests in a4 only. Not sure if this helps or complicates everything.
What do you guys think?
> setup jest testing for adhocracy4

- adhocracy4/actions/signals.py
- adhocracy4/comments/api.py
- adhocracy4/comments/serializers.py
- adhocracy4/comments/signals.py
- adhocracy4/comments_async/api.py
@fuzzylogic2000 Not sure about the deprecation warnings, could not really test as mB needs to updated to django 3 first..  what do you think?
> Ks 2021 10 issues

- adhocracy4/comments/admin.py
> adhocracy4/comments: correct position of is_blocked field

- requirements/base.txt
I guess we should also update it here?
> deps/python: update psycopg2-binary

- adhocracy4/phases/predicates.py
Not sure if these comments make sense?
> Ks 2021 12 voting phase predicates

- adhocracy4/maps/static/a4maps/a4maps_display_points.js
to fix issue in meinBerlin 
closes liqd/a4-meinberlin#4100
> display maps: leaflet.markerClusterGroup import earlier

- adhocracy4/phases/predicates.py
Needed for meinberlin_budgeting.delete_vote rule.
> phases/predicates: add phase_allows_delete_vote

- adhocracy4/filters/filters.py
- tests/filter/test_filter_widgets.py
- tests/filter/test_ordering_filters.py
Turns out: not all items can be rated...
> apps/filters: only annotate rating when item has rates

- adhocracy4/dashboard/dashboard.py
fixes https://github.com/liqd/adhocracy-plus/issues/293 (but we will have to look out for that string in mB and OPIN as well, then).
> apps/dashboard: wording fix

- adhocracy4/maps/static/a4maps/a4maps_choose_polygon_with_preset.js
> Revert "maps/a4maps_choose_polygon_with_preset: remove deprecated .modal func…"

- adhocracy4/projects/admin.py
This also fixes [#1656](https://github.com/liqd/adhocracy-plus/issues/1656) as was done [here](https://github.com/liqd/adhocracy-plus/pull/1664/commits/6c9be35bb186c8cd504f492255f866dd224ff95c) and in general in projects after the django update.
> fix django admin CK editor fields

- adhocracy4/comments_async/serializers.py
- tests/comments/test_async_api.py
> comments_async/serializers: add changing and deleting permission

- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/static/comments_async/comment_category_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
distinguish between replying and commenting
> comments_async translation keys changed and adding

- adhocracy4/polls/assets/PollQuestions.jsx
https://github.com/liqd/a4-meinberlin/issues/4220
> wording/poll: change wording for submit error

- adhocracy4/filters/filters.py
- adhocracy4/filters/mixins.py
Also fixed linting errors, the actual change is in line 109 :)
> filters: fix annotations for DistinctOrderingWithDailyRandomFilter

- adhocracy4/comments/models.py
> comments/models: fix typo

- babel.config.js
github actions failed due to this change. reverting it.
> reverting PR #1096

- adhocracy4/comments/static/comments/react_comments.jsx
- adhocracy4/comments_async/static/comments_async/index.jsx
- adhocracy4/follows/static/follows/react_follows.jsx
- adhocracy4/polls/assets/react_polls.jsx
- adhocracy4/ratings/static/ratings/react_ratings.jsx
- adhocracy4/reports/static/reports/react_reports.jsx
This reverts commit a50186fec1bedc277d7f9dc9781bdb78c55a26f6 but keeps the import syntax
> Revert "static/*: update render functions to new syntax"

- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/polls/assets/PollQuestions.jsx
add event which indicates that the terms of use have been accepted to other components
> add custom tos agreed event

- adhocracy4/actions/management/commands/create_system_actions.py
- tests/actions/test_commands.py
will fix (after cherry-picking to hotfix branch) https://github.com/liqd/a4-meinberlin/issues/4383
> apps/actions: make sure only actions for published modules are created

- adhocracy4/maps/static/a4maps/a4maps_choose_polygon_with_preset.js
- adhocracy4/polls/static/PollDashboard/EditPollChoice.jsx
- adhocracy4/polls/static/PollDashboard/EditPollManagement.jsx
- adhocracy4/polls/static/PollDashboard/EditPollOpenQuestion.jsx
- adhocracy4/polls/static/PollDashboard/EditPollQuestion.jsx
- adhocracy4/polls/static/PollDashboard/HelptextForm.jsx
- adhocracy4/polls/static/PollDetail/PollQuestion.jsx
- adhocracy4/polls/static/PollDetail/PollQuestions.jsx
- adhocracy4/static/Alert.jsx
- adhocracy4/static/ErrorList.jsx
- adhocracy4/static/FormFieldError.jsx
- adhocracy4/static/__tests__/Alert.jest.jsx
- index.js
part of fix for https://github.com/liqd/a4-meinberlin/issues/4232
> updating our jsx errors to be a11y compliant

- adhocracy4/modules/models.py
will fix (after update) https://github.com/liqd/adhocracy-plus/issues/2151
> apps/modules: make sure abbreviated string gets into translations

- adhocracy4/categories/assets/category_formset.js
Refactor to mostly remove jquery. It is still conditionally called for the select category icon element. After investigating alternatives, most options don't offer any advantage, the more accessible option that was found [here](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) would require a custom django widget and is still not actually recommended due to possible gaps in support, we can look into it as a technical backlog story.
> [#6785] categories/assets/category_formset: refactor category_formset

- Makefile
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/polls/static/PollDashboard/EditPollOpenQuestion.jsx
- adhocracy4/polls/static/PollDetail/PollQuestion.jsx
- adhocracy4/polls/static/PollDetail/PollQuestions.jsx
- adhocracy4/polls/static/PollDetail/PollResults.jsx
- package.json
hacky fix for #1103
normal fix for #1015
WILL FIX https://github.com/liqd/adhocracy-plus/issues/2239
> [issues] Poll multi select issue and makefile update

- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/static/comments_async/comment_category_edit_form.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
fixes https://github.com/liqd/adhocracy-plus/issues/2276
fixes https://github.com/liqd/a4-kosmo/issues/346
> Kl 2023 03 orga terms

- CHANGELOG.md
- adhocracy4/actions/management/commands/create_system_actions.py
- tests/actions/test_commands.py
not a draft
see https://github.com/liqd/a4-meinberlin/issues/4922
> actions: only create actions for phases and project if the project is

- adhocracy4/comments_async/static/comments_async/comment_box.jsx
> comments_async: fix broken scroll and tos callback

- .gitignore
- adhocracy4/emails/base.py
- adhocracy4/emails/tasks.py
- adhocracy4/test/helpers.py
- changelog/7601.md
- requirements/base.txt
- tests/conftest.py
to do:
- ~custom migration that removes the existing tables of the un-installed app `background_tasks`~
> [7601] Install and configure Celery

- adhocracy4/projects/models.py
- changelog/0009.md
> Hotfix topics_name property

- adhocracy4/test/factories/__init__.py
> test/factories: make TopicFactory load the TopicEnum from settings

- adhocracy4/comments_async/static/comments_async/comment.jsx
- adhocracy4/comments_async/static/comments_async/comment_box.jsx
- adhocracy4/comments_async/static/comments_async/comment_form.jsx
small issues that were found in mB since comment_form refactor
**Tasks**
> comments_async: small class name fixes after re-factor

- adhocracy4/dashboard/mixins.py
- changelog/1528.md
- tests/dashboard/test_views.py
> dashboard: save duplicate image as new instance

- requirements/base.txt
> deps: update dependency autoslug to upstream

- adhocracy4/comments_async/static/modals/UrlModal.jsx
- adhocracy4/reports/static/reports/ReportModal.jsx
- adhocracy4/static/Modal.jsx
second try at fixing https://github.com/liqd/adhocracy4/issues/1588 & https://github.com/liqd/adhocracy-plus/issues/2565
previous PR https://github.com/liqd/adhocracy4/pull/1594
> static/Modal.jsx: Handle default value for dismissOnSubmit prop

- CHANGELOG.md
> release aplus-v2406.1.1

- CHANGELOG.md
- changelog/_1111.md
- changelog/_1112.md
- changelog/_1113.md
> release aplus-v2406.3

- adhocracy4/polls/static/PollDetail/PollOpenQuestion.jsx
- changelog/8462.md
fix issue with the open question input field
> polls/PollOpenQuestion.jsx: change input type to textarea

- pytest.ini
The recommended import mode and required for some tests. Same as https://github.com/liqd/adhocracy-plus/pull/2519
**Tasks**
> pytest.ini: set import mode to importlib

- .github/workflows/django.yml
To reflect the current dev container
**Tasks**
> ci: bump to ubuntu 24.04, python 3.12, node 20

- adhocracy4/static/Alert.jsx
- changelog/8483.md
> [8483]static/alert: add div and classes for meinBerlin

- adhocracy4/polls/static/PollDashboard/EditPollManagement.jsx
- changelog/8462.md
added semantic elements and fixed checkbox
styles: 
https://github.com/liqd/a4-meinberlin/pull/5874
https://github.com/liqd/adhocracy-plus/pull/2867
https://github.com/liqd/a4-meinberlin/pull/5875
> polls: fix unregistered users checkbox

- adhocracy4/polls/static/PollDetail/ChoiceRow.jsx
- adhocracy4/polls/static/PollDetail/PollChoice.jsx
- adhocracy4/static/Captcha.jsx
- changelog/_0002.md
- make other input field work for unregistered users
- make captcha text mode react to input to make it actually work
fixes https://github.com/liqd/adhocracy-plus/issues/2906 and https://github.com/liqd/adhocracy-plus/issues/2905
**Tasks**
> some small open poll fixes

- CHANGELOG.md
- changelog/_0001.md
- changelog/_0002.md
> release aplus-v250.1.1

- adhocracy4/static/Alert.jsx
> Add title to Alert component

- adhocracy4/projects/migrations/0049_project_geos_point.py
> projects: skip point migration if no point is set

- adhocracy4/dashboard/components/forms/views.py
- adhocracy4/maps/mixins.py
- adhocracy4/maps/widgets.py
- adhocracy4/maps_react/widgets.py
- tests/maps/test_map_mixins.py
- tests/maps/test_widget.py
- tests/maps_react/test_widget.py
> refactor PointFormMixin and make MapChoosePointWidget handle geo points

- adhocracy4/projects/migrations/0049_migrate_data_from_point_to_geos_point.py
- changelog/1782.md
~~**Not ready to merge --Testing the branch with mB local setting**~~
testing done
**Tasks**
> projects/migrations: fix GIS exceptions

- adhocracy4/projects/admin.py
- changelog/_0006.md
**Tasks**
renders the map in the django admin 
before:
after:
> projects: change to GIS admin model

- CHANGELOG.md
> changelog: mb-v2504.2

- adhocracy4/comments_async/static/comments_async/ai_report.jsx
Adds hardcoded translations for english labels, per https://app.asana.com/1/1175467295883992/task/1210233803160242/comment/1210252756930201?focus=true
> ai report: add label translations hardcoded

- adhocracy4/comments_async/static/comments_async/ai_report.jsx
> Jp 2505 ai labels translations 2

- adhocracy4/polls/static/PollDashboard/EditPollChoice.jsx
- adhocracy4/polls/static/PollDashboard/EditPollManagement.jsx
- adhocracy4/polls/static/PollDashboard/EditPollOpenQuestion.jsx
- adhocracy4/polls/static/PollDashboard/EditPollQuestion.jsx
> ST2936 polls:  fix  PollQuestion deletion bug

- adhocracy4/polls/exports.py
- changelog/882.md
- tests/polls/test_exports.py
> ST884 apps/polls: make poll export efficient to avoid timeout errors

- adhocracy4/follows/static/follows/FollowButton.jsx
- adhocracy4/follows/static/follows/__tests__/FollowButton.jest.jsx
- adhocracy4/static/Alert.jsx
- changelog/828.md
> ST828 update followed project alert text

- CHANGELOG.md
- adhocracy4/maps/mixins.py
- adhocracy4/maps/static/a4maps/a4maps_address.js
- adhocracy4/maps_react/static/a4maps_react/AddressSearch.jsx
- adhocracy4/maps_react/widgets.py
- adhocracy4/static/forms/AutoComplete.jsx
- tests/conftest.py
- tests/maps/test_map_mixins.py
- tests/maps/test_widget.py
- tests/maps_react/test_widget.py
> [ST620] apps/maps: Make adjustments for new address api

- changelog/250929_svg.md
- requirements/base.txt
> Remove thumbnail svg from requirements to get rid of cairo deps
